n = input('Digite um algo: ')
print('Tipo ', type(n))
print('Tem letra? ', n.isalpha())
print('Tem número? ', n.isnumeric())
print('É AlphaNumérico? ', n.isalnum())
print('É escrito normal? ', n.islower())
